#!/usr/bin/env ruby

output = File.open('output/2.txt', 'w')

input = File.readlines('input/2.txt').map do |line|
  line.split('x').map(&:to_i)
end

paper = input.map do |dim|
  x, y, z = dim.sort
  2 * (x * y + x * z + y * z) + x * y
end

total = paper.reduce(:+)

output.write(total)
puts total

ribbon = input.map do |dim|
  x, y, z = dim.sort
  2 * (x + y) + x * y * z
end

total = ribbon.reduce(:+)

output.write("\n#{total}")
puts total

output.close
