#!/usr/bin/env ruby

require 'set'

input = File.read('input/3.txt')

class Sled
  attr_accessor :x, :y

  def initialize
    self.x, self.y = 0, 0
  end

  def location
    [x, y]
  end

  def right
    self.x += 1
  end

  def left
    self.x += -1
  end

  def up
    self.y += 1
  end

  def down
    self.y += -1
  end
end

sled = Sled.new
houses = Set.new

input.chars.each do |move|
  case move
  when '>'
    sled.right
  when '<'
    sled.left
  when '^'
    sled.up
  when 'v'
    sled.down
  end

  houses << sled.location
end

total = houses.count

File.write('output/3.txt', total)
puts total
